name: Build & Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read       # allow checkout
  pages: write         # allow Pages deployment
  id-token: write      # allow OIDC token for deploy-pages

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install & Build Frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build
          # ensure client‑side routing fallback
          cp dist/index.html dist/404.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist

  deploy:
    needs: build-and-upload
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
